create database nextflix;
show databases;
use nextflix;    
CREATE TABLE directors (
    director_id INT PRIMARY KEY AUTO_INCREMENT,
    director_name VARCHAR(255) NOT NULL
);
CREATE TABLE netflix_shows (
    show_id VARCHAR(5) PRIMARY KEY,
    type VARCHAR(10),
    title VARCHAR(255),
    director_id INT,
    cast VARCHAR(1000),
    country VARCHAR(255),
    date_added DATE,
    release_year INT,
    rating VARCHAR(10),
    duration VARCHAR(20),
    listed_in VARCHAR(255),
    description TEXT,
    FOREIGN KEY (director_id) REFERENCES directors(director_id)
);


-- Inserting values into the directors table
INSERT INTO directors (director_name) VALUES 
('Kirsten Johnson'),
('Julien Leclercq'),
('Mike Flanagan'),
('Robert Cullen'),
('Haile Gerima'),
('Andy Devonshire'),
('Theodore Melfi'),
('Kongkiat Komesiri');

-- Inserting values into the netflix_shows table
INSERT INTO netflix_shows (show_id, type, title, director_id, cast, country, date_added, release_year, rating, duration, listed_in, description) VALUES 
('s1', 'Movie', 'Dick Johnson Is Dead', 1, NULL, 'United States', '2021-09-25', 2020, 'PG-13', '90 min', 'Documentaries', 'As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'),
('s3', 'TV Show', 'Ganglands', 2, 'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera', NULL, '2021-09-24', 2021, 'TV-MA', '1 Season', 'Crime TV Shows, International TV Shows, TV Action & Adventure', 'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.'),
('s6', 'TV Show', 'Midnight Mass', 3, 'Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver', NULL, '2021-09-24', 2021, 'TV-MA', '1 Season', 'TV Dramas, TV Horror, TV Mysteries', 'The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.'),
('s7', 'Movie', 'My Little Pony: A New Generation', 4, 'Vanessa Hudgens, Kimiko Glenn, James Marsden, Sofia Carson, Liza Koshy, Ken Jeong, Elizabeth Perkins, Jane Krakowski, Michael McKean, Phil LaMarr', NULL, '2021-09-24', 2021, 'PG', '91 min', 'Children & Family Movies', 'Equestria''s divided. But a bright-eyed hero believes Earth Ponies, Pegasi and Unicorns should be pals ��� and, hoof to heart, she���s determined to prove it.'),
('s8', 'Movie', 'Sankofa', 5, 'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri', 'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia', '2021-09-24', 1993, 'TV-MA', '125 min', 'Dramas, Independent Movies, International Movies', 'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.'),
('s9', 'TV Show', 'The Great British Baking Show', 6, 'Mel Giedroyc, Sue Perkins, Mary Berry, Paul Hollywood', 'United Kingdom', '2021-09-24', 2021, 'TV-14', '9 Seasons', 'British TV Shows, Reality TV', 'A talented batch of amateur bakers face off in a 10-week competition, whipping up their best dishes in the hopes of being named the U.K.''s best.'),
('s10', 'Movie', 'The Starling', 7, 'Melissa McCarthy, Chris O''Dowd, Kevin Kline, Timothy Olyphant, Daveed Diggs, Skyler Gisondo, Laura Harrier, Rosalind Chao, Kimberly Quinn, Loretta Devine, Ravi Kapoor', 'United States', '2021-09-24', 2021, 'PG-13', '104 min', 'Comedies, Dramas', 'A woman adjusting to life after a loss contends with a feisty bird that''s taken over her garden ��� and a husband who''s struggling to find a way forward.'),
('s12', 'TV Show', 'Bangkok Breaking', 8, 'Sukollawat Kanarot, Sushar Manaying, Pavarit Mongkolpisit, Sahajak Boonthanakit, Suthipongse Thatphithakkul, Bhasaworn Bawronkirati, Daweerit Chullasapya, Waratthaya Wongchayaporn, Kittiphoom Wongpentak, Abhicha Thanachanun', NULL, '2021-09-23', 2021, 'TV-MA', '1 Season', 'Crime TV Shows, International TV Shows, TV Action & Adventure', 'Struggling to earn a living in Bangkok, a man joins an emergency rescue service and realizes he must unravel a citywide conspiracy.');


INSERT INTO netflix_shows (show_id, type, title, director_id, cast, country, date_added, release_year, rating, duration, listed_in, description) VALUES
('s13', 'Movie', 'Je Suis Karl', NULL, 'Luna Wedler, Jannis Niewühner, Milan Peschel, Edin Hasanović, Anna Fialová, Marlon Boess, Victor Boccard, Fleur Geffrier, Aziz Dyab, Mélanie Fouché, Elizaveta Maximová', 'Germany, Czech Republic', '2021-09-23', 2021, 'TV-MA', '127 min', 'Dramas, International Movies', 'After most of her family is murdered in a terrorist bombing, a young woman is unknowingly lured into joining the very group that killed them.'),
('s14', 'Movie', 'Confessions of an Invisible Girl', NULL, 'Klara Castanho, Lucca Picon, Júlia Gomes, Marcus Bessa, Kiria Malheiros, Fernanda Concon, Gabriel Lima, Caio Cabral, Leonardo Cidade, Jade Cardozo', NULL, '2021-09-22', 2021, 'TV-PG', '91 min', 'Children & Family Movies, Comedies', 'When the clever but socially-awkward Tetê joins a new school, she''ll do anything to fit in. But the queen bee among her classmates has other ideas.'),
('s15', 'TV Show', 'Crime Stories: India Detectives', NULL, NULL, NULL, '2021-09-22', 2021, 'TV-MA', '1 Season', 'British TV Shows, Crime TV Shows, Docuseries', 'Cameras following Bengaluru police on the job offer a rare glimpse into the complex and challenging inner workings of four major crime investigations'),
('s16', 'TV Show', 'Dear White People', NULL, 'Logan Browning, Brandon P. Bell, DeRon Horton, Antoinette Robertson, John Patrick Amedori, Ashley Blaine Featherson, Marque Richardson, Giancarlo Esposito', 'United States', '2021-09-22', 2021, 'TV-MA', '4 Seasons', 'TV Comedies, TV Dramas', 'Students of color navigate the daily slights and slippery politics of life at an Ivy League college that''s not nearly as "post-racial" as it thinks'),
('s17', 'Movie', 'Europe''s Most Dangerous Man: Otto Skorzeny in Spain', NULL, NULL, NULL, '2021-09-22', 2020, 'TV-MA', '67 min', 'Documentaries, International Movies', 'Declassified documents reveal the post-WWII life of Otto Skorzeny, a close Hitler ally who escaped to Spain and became an adviser to world presidents'),
('s18', 'TV Show', 'Falsa identidad', NULL, 'Luis Ernesto Franco, Camila Sodi, Sergio Goyri, Samadhi Zendejas, Eduardo Yáñez, Sonya Smith, Alejandro Camacho, Azela Robinson, Uriel del Toro, Géraldine Bazán, Gabriela Roel, Marcus Ornellas', 'Mexico', '2021-09-22', 2020, 'TV-MA', '2 Seasons', 'Crime TV Shows, Spanish-Language TV Shows, TV Dramas', 'Strangers Diego and Isabel flee their home in Mexico and pretend to be a married couple to escape his drug-dealing enemies and her abusive husband'),
('s19', 'Movie', 'Intrusion', NULL, 'Freida Pinto, Logan Marshall-Green, Robert John Burke, Megan Elisabeth Kelly, Sarah Minnich, Hayes Hargrove, Mark Sivertsen, Brandon Fierro, Antonio Valles, Clint Obenchain', NULL, '2021-09-22', 2021, 'TV-14', '94 min', 'Thrillers', 'After a deadly home invasion at a couple’s new dream house, the traumatized wife searches for answers – and learns the real danger is just beginning'),
('s20', 'TV Show', 'Jaguar', NULL, 'Blanca Suárez, Iván Marcos, Óscar Casas, Adrián Lastra, Francesc Garrido, Stefan Weinert, Julia Müller, Alicia Chojnowski', NULL, '2021-09-22', 2021, 'TV-MA', '1 Season', 'International TV Shows, Spanish-Language TV Shows, TV Action & Adventure', 'In the 1960s, a Holocaust survivor joins a group of self-trained spies who seek justice against Nazis fleeing to Spain to hide after WWII'),
('s21', 'TV Show', 'Monsters Inside: The 24 Faces of Billy Milligan', NULL, NULL, NULL, '2021-09-22', 2021, 'TV-14', '1 Season', 'Crime TV Shows, Docuseries, International TV Shows', 'In the late 1970s, an accused serial rapist claims multiple personalities control his behavior, setting off a legal odyssey that captivates America');

INSERT INTO netflix_shows (show_id, type, title, director_id, cast, country, date_added, release_year, rating, duration, listed_in, description) VALUES
 ('s22', 'TV Show', 'Resurrection: Ertugrul', NULL, 'Engin Altan Düzyatan, Serdar Gökhan, Hülya Darcan, Kaan Taşaner, Esra Bilgiç, Osman Soykut, Serdar Deniz, Cengiz Coşkun, Reshad Strik, Hande Subaşı', 'Turkey', '2021-09-22', 2018, 'TV-14', '5 Seasons', 'International TV Shows, TV Action & Adventure, TV Dramas', 'When a good deed unwittingly endangers his clan, a 13th-century Turkish warrior agrees to fight a sultan''s enemies in exchange for new tribal land.'),
 ('s23', 'Movie', 'Avvai Shanmughi', NULL, 'Kamal Hassan, Meena, Gemini Ganesan, Heera Rajgopal, Nassar, S.P. Balasubrahmanyam', NULL, '2021-09-21', 1996, 'TV-PG', '161 min', 'Comedies, International Movies', 'Newly divorced and denied visitation rights with his daughter, a doting father disguises himself as a gray-haired nanny in order to spend time with her.'),
 ('s24', 'Movie', 'Go! Go! Cory Carson: Chrissy Takes the Wheel', NULL, 'Maisie Benson, Paul Killam, Kerry Gudjohnsen, AC Lim', NULL, '2021-09-21', 2021, 'TV-Y', '61 min', 'Children & Family Movies', 'From arcade games to sled days and hiccup cures, Cory Carson’s curious little sister Chrissy speeds off on her own for fun and adventure all over town!'),
 ('s25', 'Movie', 'Jeans', NULL, 'Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi, Nassar', 'India', '2021-09-21', 1998, 'TV-14', '166 min', 'Comedies, International Movies, Romantic Movies', 'When the father of the man she loves insists that his twin sons marry twin sisters, a woman creates an alter ego that might be a bit too convincing.'),
 ('s26', 'TV Show', 'Love on the Spectrum', NULL, 'Brooke Satchwell', 'Australia', '2021-09-21', 2021, 'TV-14', '2 Seasons', 'Docuseries, International TV Shows, Reality TV', 'Finding love can be hard for anyone. For young adults on the autism spectrum, exploring the unpredictable world of dating is even more complicated.'),
 ('s27', 'Movie', 'Minsara Kanavu', NULL, 'Arvind Swamy, Kajol, Prabhu Deva, Nassar, S.P. Balasubrahmanyam, Girish Karnad', NULL, '2021-09-21', 1997, 'TV-PG', '147 min', 'Comedies, International Movies, Music & Musicals', 'A tangled love triangle ensues when a man falls for a woman studying to become a nun ��� and she falls for the friend he enlists to help him pursue her.');


INSERT INTO netflix_shows (show_id, type, title, director_id, cast, country, date_added, release_year, rating, duration, listed_in, description) VALUES
 ('s28', 'Movie', 'Grown Ups', NULL, 'Adam Sandler, Kevin James, Chris Rock, David Spade, Rob Schneider, Salma Hayek, Maria Bello, Maya Rudolph, Colin Quinn, Tim Meadows, Joyce Van Patten', 'United States', '2021-09-20', 2010, 'PG-13', '103 min', 'Comedies', 'Mourning the loss of their beloved junior high basketball coach, five middle-aged pals reunite at a lake house and rediscover the joys of being a kid.'),
 ('s29', 'Movie', 'Dark Skies', NULL, 'Keri Russell, Josh Hamilton, J.K. Simmons, Dakota Goyo, Kadan Rockett, L.J. Benet, Rich Hutchman, Myndy Crist, Annie Thurman, Jake Brennan', 'United States', '2021-09-19', 2013, 'PG-13', '97 min', 'Horror Movies, Sci-Fi & Fantasy', 'A family’s idyllic suburban life shatters when an alien force invades their home, and as they struggle to convince others of the deadly threat.'),
 ('s30', 'Movie', 'Paranoia', NULL, 'Liam Hemsworth, Gary Oldman, Amber Heard, Harrison Ford, Lucas Till, Embeth Davidtz, Julian McMahon, Josh Holloway, Richard Dreyfuss, Angela Sarafyan', 'United States, India, France', '2021-09-19', 2013, 'PG-13', '106 min', 'Thrillers', 'Blackmailed by his company''s CEO, a low-level employee finds himself forced to spy on the boss''s rival and former mentor.'),
 ('s31', 'Movie', 'Ankahi Kahaniya', NULL, 'Abhishek Banerjee, Rinku Rajguru, Delzad Hiwale, Kunal Kapoor, Zoya Hussain, Nikhil Dwivedi, Palomi Ghosh', NULL, '2021-09-17', 2021, 'TV-14', '111 min', 'Dramas, Independent Movies, International Movies', 'As big city life buzzes around them, lonely souls discover surprising sources of connection and companionship in three tales of love, loss and longing.'),
 ('s32', 'TV Show', 'Chicago Party Aunt', NULL, 'Lauren Ash, Rory O''Malley, RuPaul Charles, Jill Talley, Ike Barinholtz, Jon Barinholtz, Matthew Craig, Bob Odenkirk, Mike Hagerty, Katie Rich, Chris Witaske', NULL, '2021-09-17', 2021, 'TV-MA', '1 Season', 'TV Comedies', 'Chicago Party Aunt Diane is an idolized troublemaker with a talent for avoiding adulthood ��� and a soft spot for her soul-searching nephew.'),
 ('s33', 'TV Show', 'Sex Education', NULL, 'Asa Butterfield, Gillian Anderson, Ncuti Gatwa, Emma Mackey, Connor Swindells, Kedar Williams-Stirling, Alistair Petrie', 'United Kingdom', '2021-09-17', 2020, 'TV-MA', '3 Seasons', 'British TV Shows, International TV Shows, TV Comedies', 'Insecure Otis has all the answers when it comes to sex advice, thanks to his therapist mom. So rebel Maeve proposes a school sex-therapy clinic.'),
 ('s34', 'TV Show', 'Squid Game', NULL, 'Lee Jung-jae, Park Hae-soo, Wi Ha-jun, Oh Young-soo, Jung Ho-yeon, Heo Sung-tae, Kim Joo-ryoung, Tripathi Anupam, You Seong-joo, Lee You-mi', NULL, '2021-09-17', 2021, 'TV-MA', '1 Season', 'International TV Shows, TV Dramas, TV Thrillers', 'Hundreds of cash-strapped players accept a strange invitation to compete in children''s games. Inside, a tempting prize awaits ��� with deadly high stakes.'),
 ('s35', 'TV Show', 'Tayo and Little Wizards', NULL, 'Dami Lee, Jason Lee, Bommie Catherine Han, Jennifer Waescher, Nancy Kim', NULL, '2021-09-17', 2020, 'TV-Y7', '1 Season', 'Kids'' TV', 'Tayo speeds into an adventure when his friends get kidnapped by evil magicians invading their city in search of a magical gemstone.'),
 ('s36', 'Movie', 'The Father Who Moves Mountains', NULL, 'Adrian Titieni, Elena Purea, Judith State, Valeriu Andriu, Tudor Smoleanu, Virgil Aioanei, Radu Botar, Petronela Grigorescu, Bogdan Nechifor, Cristian Bota', NULL, '2021-09-17', 2021, 'TV-MA', '110 min', 'Dramas, International Movies, Thrillers', 'When his son goes missing during a snowy hike in the mountains, a retired intelligence officer will stop at nothing ��� and risk everything ��� to find him.'),
 ('s37', 'Movie', 'The Stronghold', NULL, 'Gilles Lellouche, Karim Leklou, François Civil, Adèle Exarchopoulos, Kenza Fortas, Cyril Lecomte, Michaël Abiteboul, Idir Azougli, Vincent Darmuzey, Jean-Yves Berteloot', NULL, '2021-09-17', 2021, 'TV-MA', '105 min', 'Action & Adventure, Dramas, International Movies', 'Tired of the small-time grind, three Marseille cops get a chance to bust a major drug network. But lines blur when a key informant makes a big ask.');


INSERT INTO netflix_shows (show_id, type, title, director_id, cast, country, date_added, release_year, rating, duration, listed_in, description) VALUES
  ('s38', 'TV Show', 'Angry Birds', NULL, 'Antti P����kk��nen, Helj�� Heikkinen, Lynne Guaglione, Pasi Ruohonen, Rauno Ahonen', 'Finland', '2021-09-16', 2018, 'TV-Y7', '1 Season', 'Kids'' TV, TV Comedies', 'Birds Red, Chuck and their feathered friends have lots of adventures while guarding eggs in their nest that pesky pigs keep trying to steal.'),
  ('s39', 'Movie', 'Birth of the Dragon', 1, 'Billy Magnussen, Ron Yuan, Qu Jingjing, Terry Chen, Vanness Wu, Jin Xing, Philip Ng, Xia Yu, Yu Xia', 'China, Canada, United States', '2021-09-16', 2017, 'PG-13', '96 min', 'Action & Adventure, Dramas', 'A young Bruce Lee angers kung fu traditionalists by teaching outsiders, leading to a showdown with a Shaolin master in this film based on real events.');

INSERT INTO netflix_shows (show_id, type, title, director_id, cast, country, date_added, release_year, rating, duration, listed_in, description) VALUES
('s40', 'TV Show', 'Chhota Bheem', NULL, 'Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil', 'India', '2021-09-16', 2021, 'TV-Y7', '3 Seasons', 'Kids'' TV', 'A brave, energetic little boy with superhuman powers leads his friends on exciting adventures to guard their fellow Dholakpur villagers from evil.'),
('s41', 'TV Show', 'He-Man and the Masters of the Universe', NULL, 'Yuri Lowenthal, Kimberly Brooks, Antony Del Rio, Trevor Devall, Ben Diskin, Grey Griffin, David Kaye, Tom Kenny, Judy Alice Lee, Roger Craig Smith, Fred Tatasciore', 'United States', '2021-09-16', 2021, 'TV-Y7', '1 Season', 'Kids'' TV, TV Sci-Fi & Fantasy', 'Mighty teen Adam and his heroic squad of misfits discover the legendary power of Grayskull ��� and their destiny to defend Eternia from sinister Skeletor.'),
('s42', 'Movie', 'Jaws', NULL, 'Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary, Murray Hamilton, Carl Gottlieb, Jeffrey Kramer, Susan Backlinie, Jonathan Filley, Ted Grossman', 'United States', '2021-09-16', 1975, 'PG', '124 min', 'Action & Adventure, Classic Movies, Dramas', 'When an insatiable great white shark terrorizes Amity Island, a police chief, an oceanographer and a grizzled shark hunter seek to destroy the beast.'),
('s43', 'Movie', 'Jaws 2', NULL, 'Roy Scheider, Lorraine Gary, Murray Hamilton, Joseph Mascolo, Jeffrey Kramer, Collin Wilcox Paxton, Ann Dusenberry, Mark Gruner, Barry Coe, Susan French', 'United States', '2021-09-16', 1978, 'PG', '116 min', 'Dramas, Horror Movies, Thrillers', 'Four years after the last deadly shark attacks, police chief Martin Brody fights to protect Amity Island from another killer great white.'),
('s44', 'Movie', 'Jaws 3', NULL, 'Dennis Quaid, Bess Armstrong, Simon MacCorkindale, Louis Gossett Jr., John Putch, Lea Thompson, P.H. Moriarty, Dan Blasko, Liz Morris, Lisa Maurer', 'United States', '2021-09-16', 1983, 'PG', '98 min', 'Action & Adventure, Horror Movies, Thrillers', 'After the staff of a marine theme park try to capture a young great white shark, they discover its mother has invaded the enclosure and is out for blood.'),
('s45', 'Movie', 'Jaws: The Revenge', NULL, 'Lorraine Gary, Lance Guest, Mario Van Peebles, Karen Young, Michael Caine, Judith Barsi, Mitchell Anderson, Lynn Whitfield', 'United States', '2021-09-16', 1987, 'PG-13', '91 min', 'Action & Adventure, Horror Movies, Thrillers', 'After another deadly shark attack, Ellen Brody has had enough of Amity Island and moves to the Caribbean ��� but a great white shark follows her there.'),
('s46', 'Movie', 'My Heroes Were Cowboys', NULL, NULL, NULL, '2021-09-16', 2021, 'PG', '23 min', 'Documentaries', 'Robin Wiltshire''s painful childhood was rescued by Westerns. Now he lives on the frontier of his dreams, training the horses he loves for the big screen.'),
('s47', 'Movie', 'Safe House', NULL, 'Denzel Washington, Ryan Reynolds, Vera Farmiga, Brendan Gleeson, Sam Shepard, Rub��n Blades, Nora Arnezeder, Robert Patrick, Liam Cunningham, Joel Kinnaman', 'South Africa, United States, Japan', '2021-09-16', 2012, 'R', '115 min', 'Action & Adventure', 'Young CIA operative Matt Weston must get a dangerous criminal out of an agency safe house that''s come under attack and get him to a securer location.'),
('s48', 'TV Show', 'The Smart Money Woman', NULL, 'Osas Ighodaro, Ini Dima-Okojie, Kemi Lala Akindoju, Toni Tones, Ebenezer Eno, Eso Okolocha DIke, Patrick Diabuah, Karibi Fubara, Temisan Emmanuel, Timini Egbuson', NULL, '2021-09-16', 2020, 'TV-MA', '1 Season', 'International TV Shows, Romantic TV Shows, TV Comedies', 'Five glamorous millennials strive for success as they juggle careers, finances, love and friendships. Based on Arese Ugwu''s 2016 best-selling novel.'),
('s49', 'Movie', 'Training Day', NULL, 'Denzel Washington, Ethan Hawke, Scott Glenn, Tom Berenger, Harris Yulin, Raymond J. Barry, Cliff Curtis, Dr. Dre, Snoop Dogg, Macy Gray, Eva Mendes', 'United States', '2021-09-16', 2001, 'R', '122 min', 'Dramas, Thrillers', 'A rookie cop with one day to prove himself to a veteran LAPD narcotics officer receives a crash course in his mentor''s questionable brand of justice.'),
('s50', 'TV Show', 'Castle and Castle', NULL, 'Richard Mofe-Damijo, Dakore Akande, Bimbo Manuel, Blossom Chukwujekwu, Deyemi Okanlawon, Etim Effiong, Denola Grey, Duke Akintola, Eku Edewor, Ade Laoye, Anee Icha, Kevin Ushi, Jude Chukwuka, Amanda Afolabi', 'Nigeria', '2021-09-15', 2021, 'TV-MA', '2 Seasons', 'International TV Shows, TV Dramas', 'A pair of high-powered, successful lawyers find themselves defending opposite interests of the justice system, causing a strain on their happy marriage.');

select * from netflix_shows;
